const Article = [
  {
    id:1,
    title:"CSS3新属性",
    tag:"HTML&CSS",
    date:"2016-06-02",
    description:"CSS3新增了很多属性，整理了一下",
    content:Article1
  },
  {
    id:2,
    title:"CSS居中问题",
    tag:"HTML&CSS",
    date:"2016-04-06",
    description:"在学习过程中遇到的CSS居中问题",
    content:Article2
  },
  {
    id:3,
    title:"JavaScript随记",
    tag:"JavaScript",
    date:"2016-04-15",
    description:"JavaScript基础知识",
    content:Article3
  },
  {
    id:4,
    title:"jQuery中重要的方法",
    tag:"jQuery",
    date:"2016-04-25",
    description:"学习过程中对jQuery某些方法的整理",
    content:Article4
  },
  {
    id:5,
    title:"React入门",
    tag:"React",
    date:"2016-05-05",
    description:"React 基本语法入门",
    content:Article5
  },
  {
    id:6,
    title:"jQuery插件",
    tag:"jQuery",
    date:"2016-06-15",
    description:"fullPage.js",
    content:Article6
  }
];
